/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Remembers and retrieves a value by a given name, or the value generated by `getValue` if the name doesn't exist.
 * The return type is inferred from the return type of `getValue`.
 */
export function remember<Value>(name: string, getValue: () => Value): Value {
  const thusly = globalThis as any
  thusly.__singletons ??= new Map()
  if (!thusly.__singletons.has(name)) {
    thusly.__singletons.set(name, getValue())
  }
  return thusly.__singletons.get(name)
}
